# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_prepare_date', models.DateField(help_text='Date of Proposal', verbose_name='Proposal Date')),
                ('proposal_no', models.CharField(help_text='No of Proposal', max_length=20, verbose_name='Proposal No')),
                ('customer_name_proposal', models.CharField(help_text='Enter the customer name', max_length=100, verbose_name='Customer Name')),
                ('description_of_proposal', models.TextField(help_text='Proposal Description', verbose_name='Description of Proposal')),
                ('proposal_submit_date', models.DateField(help_text='Date of Proposal', verbose_name='Proposal Date')),
                ('submit_year', models.PositiveIntegerField(blank=True, editable=False, help_text='Auto-filled year from submit date', null=True, verbose_name='Submit Year')),
                ('submit_by', models.CharField(choices=[('Physically', 'Physically'), ('By Email', 'By Email')], help_text='Select the submit process', max_length=10, verbose_name='Submit')),
                ('proposal_amount', models.DecimalField(decimal_places=2, default=0, help_text='Proposal amount', max_digits=14)),
                ('team', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text='Team responsible for the proposal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this proposal record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='Manager Sales')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this proposal record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text="Defines the user's role in proposal operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposal Role Profile',
                'verbose_name_plural': 'Proposal Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
