# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_client', models.CharField(help_text='Name of the client', max_length=100, unique=True, verbose_name='Client Name')),
                ('client_address', models.CharField(help_text='Client site address', max_length=200, verbose_name='Client Address')),
                ('contact_person_name', models.CharField(help_text='Primary contact person for the client', max_length=100, verbose_name='Contact Person Name')),
                ('contact_person_number', models.CharField(help_text='Phone number of the contact person', max_length=20, verbose_name='Contact Person Number')),
                ('team', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_construction', help_text='Team responsible for this client', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this client record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this client record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text="Defines the user's role in client operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Role Profile',
                'verbose_name_plural': 'Client Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
