# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date_cba', models.DateField(help_text='Bill Date', verbose_name='Bill Date')),
                ('bill_no_cba', models.CharField(help_text='Bill Number', max_length=100, verbose_name='Bill No')),
                ('vat_ait_cba', models.CharField(choices=[('Include', 'Include'), ('Exclude', 'Exclude')], help_text='VAT + AIT combined', max_length=10, verbose_name='VAT + AIT')),
                ('bill_amount_cba', models.DecimalField(decimal_places=2, help_text='Bill Amount', max_digits=14, verbose_name='Bill Amount')),
                ('vat_ait_amount_cba', models.DecimalField(decimal_places=2, help_text='VAT & AIT Amount', max_digits=14, verbose_name='VAT & AIT Amount')),
                ('actual_bill_amount_cba', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated field', max_digits=14)),
                ('team', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text='Team responsible for this cba', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('client_name_cba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cba_client_name_cba', to='ctv.ctv', verbose_name='Client Name')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this cba record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cba_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cba_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Manager Sales')),
                ('project_id_cba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cba_project_id_cba', to='ctv.ctv', verbose_name='Project ID')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this cba record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cba_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('wo_no_cba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cba_wo_no_cba', to='ctv.ctv', verbose_name='WO Number')),
            ],
            options={
                'verbose_name': 'CBA',
                'verbose_name_plural': 'CBA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CbaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text="Defines the user's role in cba operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cba_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CBA Role Profile',
                'verbose_name_plural': 'CBA Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
