# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cba', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the letter', verbose_name='Letter Date')),
                ('recipient_name', models.CharField(help_text='Full name of the recipient', max_length=150, verbose_name='Recipient Name')),
                ('recipient_designation', models.CharField(blank=True, help_text='Designation of the recipient', max_length=150, null=True, verbose_name='Recipient Designation')),
                ('recipient_address', models.TextField(blank=True, help_text='Address of the recipient', null=True, verbose_name='Recipient Address')),
                ('subject', models.CharField(default='Subject: Request for Bill – Supply of Design & Drawing', help_text='Subject line of the letter', max_length=255, verbose_name='Subject')),
                ('recipient_salutation', models.CharField(default='Dear Sir', help_text='Salutation used in the letter', max_length=50, verbose_name='Salutation')),
                ('body', models.TextField(default='We acknowledge receipt of the design and drawing materials supplied by your office in connection with our project requirements. To complete our records and proceed with payment formalities, we kindly request you to issue the corresponding bill/invoice for the supplied design and drawing.\n\nPlease ensure the bill includes:\n\nReference to the project name and requisition/order number\n\nDate of supply\n\nDetailed description of the design and drawing provided\n\nApplicable charges and payment terms\n\nWe would appreciate receiving the bill at your earliest convenience so that we may process it without delay.\n\nThank you for your cooperation.\n\nSincerely,', help_text='Main content of the letter', verbose_name='Letter Body')),
                ('sender_name', models.CharField(help_text='Full name of the sender', max_length=150, verbose_name='Sender Name')),
                ('sender_designation', models.CharField(blank=True, help_text='Designation of the sender', max_length=150, null=True, verbose_name='Sender Designation')),
                ('sender_company_name', models.CharField(blank=True, help_text='Company name of the sender', max_length=150, null=True, verbose_name='Sender Company Name')),
                ('remarks', models.TextField(default='NA', help_text='Remarks', max_length=255, verbose_name='Remarks')),
                ('team', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text='Team responsible for this letter', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('bill_no_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_bill_no_letter', to='cba.cba', verbose_name='Bill No')),
                ('client_name_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_client_name_letter', to='cba.cba', verbose_name='Client Name')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this letter record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter', to=settings.AUTH_USER_MODEL, verbose_name='Manager Sales')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this letter record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('wo_no_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letter_wo_no_letter', to='cba.cba', verbose_name='WO No')),
            ],
            options={
                'verbose_name': 'Letter',
                'verbose_name_plural': 'Letter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LetterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text="Defines the user's role in letter operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='letter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letter Role Profile',
                'verbose_name_plural': 'Letter Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
