# Generated by Django 5.2.1 on 2026-06-08 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('po', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_unit_sb', models.CharField(help_text='Unit of the resource (auto or manual entry)', max_length=20, verbose_name='Resource Unit')),
                ('po_quantity_sb', models.DecimalField(decimal_places=2, help_text='Quantity of the resource', max_digits=10, verbose_name='Quantity based on PO')),
                ('unit_price_sb', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('receive_date_sb', models.DateField(help_text='Date of Receive', verbose_name='Receive Date')),
                ('actual_receive_quantity_sb', models.DecimalField(decimal_places=2, help_text='Quantity of the resource', max_digits=10, verbose_name='Actual Receive Quantity')),
                ('bill_amount_sb', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated as-actual_receive_quantity_sb × unit_price_sb', max_digits=14)),
                ('team', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text='Team responsible for this SB', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sbs_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sbs', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('po_number_sb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sb_po_number_sb', to='po.po', verbose_name='PO Number')),
                ('project_name_sb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sb_project_name_sb', to='po.po', verbose_name='Project Name')),
                ('resource_name_sb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sb_resource_name_sb', to='po.po', verbose_name='Resource Name')),
                ('supplier_name_sb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sb_supplier_name_sb', to='po.po', verbose_name='Supplier Name')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sbs_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'SB',
                'verbose_name_plural': 'SBs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SbProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text="Defines the user's role in sb operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sb_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SB Role Profile',
                'verbose_name_plural': 'SB Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
