# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_resource', models.CharField(help_text='Name of the resource', max_length=100, unique=True, verbose_name='Resource Name')),
                ('unit', models.CharField(choices=[('bag', 'Bag'), ('pcs', 'Pcs'), ('nos', 'Nos'), ('kg', 'Kg'), ('ltr', 'Ltr'), ('sft', 'Sft'), ('cft', 'Cft'), ('bundle', 'Bundle'), ('ton', 'Ton')], help_text='Select the measurement unit', max_length=10, verbose_name='Unit')),
                ('resource_group', models.CharField(choices=[('civil_work_resource', 'Civil Work Resource'), ('sanitary_work_resource', 'Sanitary Work Resource'), ('electrical_work_resource', 'Electrical Work Resource')], help_text='Select the resource group', max_length=30, verbose_name='Resource Group')),
                ('team', models.CharField(choices=[('manager_construction', 'Manager Construction'), ('manager_sales', 'Manager Sales')], default='manager_construction', help_text='Team responsible for this resource', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this resource record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this resource record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_construction', 'Manager Construction'), ('manager_sales', 'Manager Sales')], default='manager_construction', help_text="Defines the user's role in resource operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resource_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Role Profile',
                'verbose_name_plural': 'Resource Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
