# Generated by Django 5.2.1 on 2026-06-09 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name_rip', models.CharField(help_text='Unit of measure (auto from Resource)', max_length=50, verbose_name='Unit')),
                ('resource_name_rip', models.CharField(help_text='Unit of measure (auto from Resource)', max_length=50, verbose_name='Unit')),
                ('resource_unit_rip', models.CharField(help_text='Unit of measure (auto from Resource)', max_length=50, verbose_name='Unit')),
                ('supplier_name_rip', models.CharField(help_text='Unit of measure (auto from Resource)', max_length=50, verbose_name='Unit')),
                ('base_price_rip', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Price')),
                ('increase_decrease_price_rip', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Increase/Decrease Amount')),
                ('actual_base_price_rip', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated cumulatively', max_digits=14)),
                ('effective_from', models.DateField(verbose_name='Price Change Date')),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('team', models.CharField(default='manager_procurement', help_text='Role/team associated with this RIP record', max_length=50, verbose_name='Team')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rips_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_procurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rips', to=settings.AUTH_USER_MODEL, verbose_name='Manager Procurement')),
                ('project_resource_supplier_name_rip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rip_project_name_rip', to='rbp.rbp', verbose_name='Project Name (RBP)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rips_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Resource Price',
                'verbose_name_plural': 'Resource Prices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_procurement', 'Manager Procurement')], default='manager_procurement', help_text="Defines the user's role in RIP operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rip_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RIP Role Profile',
                'verbose_name_plural': 'RIP Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
