# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceEventProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text="Defines the user's role in price event operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_event_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Price Event Role Profile',
                'verbose_name_plural': 'Price Event Role Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePriceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('increase_decrease_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_price', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('team', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text='Team responsible for this resource', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_price_events', to=settings.AUTH_USER_MODEL)),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_event_resources', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_price_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Price Event',
                'verbose_name_plural': 'Resource Price Events',
                'ordering': ['-effective_from'],
            },
        ),
    ]
