# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ctv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id_ctv', models.CharField(help_text='Project ID', max_length=100, verbose_name='Project ID')),
                ('wo_no_ctv', models.CharField(help_text='Work Order Number', max_length=100, verbose_name='WO No')),
                ('description_work_ctv', models.TextField(help_text='Description of Work', verbose_name='Work Description')),
                ('start_date_ctv', models.DateField(help_text='Start Date of the project', verbose_name='Start Date')),
                ('finish_date_ctv', models.DateField(help_text='Finish Date of the project', verbose_name='Finish Date')),
                ('contract_value_ctv', models.DecimalField(decimal_places=2, help_text='Contract Value', max_digits=15, verbose_name='Contract Value')),
                ('vat_ait_ctv', models.CharField(choices=[('Include', 'Include'), ('Exclude', 'Exclude')], help_text='VAT + AIT combined', max_length=10, verbose_name='VAT + AIT')),
                ('vat_ctv', models.CharField(choices=[('6.5%', '6.5%'), ('0%', '0%')], help_text='VAT', max_length=10, verbose_name='VAT')),
                ('ait_ctv', models.CharField(choices=[('13%', '13%'), ('0%', '0%')], help_text='AIT', max_length=10, verbose_name='AIT')),
                ('vat_ait_amount_ctv', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='VAT & AIT Amount', max_digits=14)),
                ('actual_contract_value_ctv', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Actual Contract Value after VAT/AIT', max_digits=14)),
                ('team', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text='Team responsible for this contract', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('client_name_ctv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctv_client_name_ctv', to='pt.pt', verbose_name='Client Name')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this contract record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctv_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctv_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Manager Sales')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this contract record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ctv_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Contract Value (CTV)',
                'verbose_name_plural': 'Contract Values (CTV)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CtvProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text="Defines the user's role in CTV operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ctv_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CTV Role Profile',
                'verbose_name_plural': 'CTV Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
