# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='NA', max_length=100)),
                ('component_name', models.CharField(default='NA', max_length=100)),
                ('component_id', models.CharField(default='NA', max_length=50)),
                ('pai_cb', models.FloatField(default=3.141592653589793)),
                ('radius_cb_mm', models.FloatField(default=0)),
                ('height_cb_mm', models.FloatField(default=0)),
                ('number_cb', models.IntegerField(default=0)),
                ('length_sb_mm', models.FloatField(default=0)),
                ('breadth_sb_mm', models.FloatField(default=0)),
                ('height_sb_mm', models.FloatField(default=0)),
                ('number_sb', models.IntegerField(default=0)),
                ('base_tb_mm', models.FloatField(default=0)),
                ('perpendicular_tb_mm', models.FloatField(default=0)),
                ('height_tb_mm', models.FloatField(default=0)),
                ('number_tb', models.IntegerField(default=0)),
                ('length1_trb_mm', models.FloatField(default=0)),
                ('length2_trb_mm', models.FloatField(default=0)),
                ('breadth_trb_mm', models.FloatField(default=0)),
                ('height_trb_mm', models.FloatField(default=0)),
                ('number_trb', models.IntegerField(default=0)),
                ('location_dq', models.CharField(default='NA', max_length=100)),
                ('component_name_dq', models.CharField(default='NA', max_length=100)),
                ('component_id_dq', models.CharField(default='NA', max_length=50)),
                ('length_dq_mm', models.FloatField(default=0)),
                ('breadth_dq_mm', models.FloatField(default=0)),
                ('height_dq_mm', models.FloatField(default=0)),
                ('number_dq', models.IntegerField(default=0)),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculation in Model', max_digits=14)),
                ('quantity_with_dry_volume', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculation in Model', max_digits=14)),
                ('type_casting', models.CharField(choices=[('manual', 'Manual'), ('rmc', 'RMC')], default='manual', help_text='Defines casting type', max_length=20)),
                ('casting_rmc', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto show casting_rmc', max_digits=14)),
                ('casting_manual', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto show casting_manual', max_digits=14)),
                ('ratio_sum_a', models.CharField(choices=[('0', ''), ('5.5', '5.5'), ('7', '7'), ('10', '10')], default='0', help_text='Defines the ratio sum a', max_length=20)),
                ('ratio_sum_b', models.CharField(choices=[('0', ''), ('5.5', '5.5'), ('7', '7'), ('10', '10')], default='0', help_text='Defines the ratio sum b', max_length=20)),
                ('ratio_sum_c', models.CharField(choices=[('0', ''), ('5.5', '5.5'), ('7', '7'), ('10', '10')], default='0', help_text='Defines the ratio sum c', max_length=20)),
                ('cement_design', models.CharField(choices=[('0%', '0%'), ('100%', '100%')], default='0%', help_text='Defines the cement design ratio', max_length=20)),
                ('sylhet_sand_design', models.CharField(choices=[('0%', '0%'), ('100%', '100%'), ('75%', 'Three-quarter strength'), ('50%', 'Half strength'), ('25%', 'Quarter strength')], default='0%', help_text='Defines the Sylhet sand design ratio', max_length=20)),
                ('local_sand_design', models.CharField(choices=[('0%', '0%'), ('100%', '100%'), ('75%', 'Three-quarter strength'), ('50%', 'Half strength'), ('25%', 'Quarter strength')], default='0%', help_text='Defines the local sand design ratio', max_length=20)),
                ('stone_20mm_design', models.CharField(choices=[('0%', '0%'), ('100%', '100%'), ('75%', 'Three-quarter strength'), ('50%', 'Half strength'), ('25%', 'Quarter strength')], default='0%', help_text='Defines the 20mm stone design ratio', max_length=20)),
                ('stone_16mm_design', models.CharField(choices=[('0%', '0%'), ('100%', '100%'), ('75%', 'Three-quarter strength'), ('50%', 'Half strength'), ('25%', 'Quarter strength')], default='0%', help_text='Defines the 16mm stone design ratio', max_length=20)),
                ('stone_12mm_design', models.CharField(choices=[('0%', '0%'), ('100%', '100%'), ('75%', 'Three-quarter strength'), ('50%', 'Half strength'), ('25%', 'Quarter strength')], default='0%', help_text='Defines the 12mm stone design ratio', max_length=20)),
                ('cement', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto show cement weight', max_digits=14)),
                ('sylhet_sand', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto show sylhet sand weight', max_digits=14)),
                ('local_sand', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto show local sand weight', max_digits=14)),
                ('stone_20mm', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto show stone 20mm weight', max_digits=14)),
                ('stone_16mm', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto show stone 16mm weight', max_digits=14)),
                ('stone_12mm', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto show stone 12mm weight', max_digits=14)),
                ('team', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text='Team responsible for this casting', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this casting record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='castings_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='castings', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('project_name_casting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casting_project_name_casting', to='project.project', verbose_name='Project Name')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this casting record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='castings_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Casting',
                'verbose_name_plural': 'Castings',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CastingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text="Defines the user's role in casting operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='casting_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Casting Role Profile',
                'verbose_name_plural': 'Casting Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
