# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('resource', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rbp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_unit_rbp', models.CharField(help_text='Unit of measure (auto from Resource)', max_length=50, verbose_name='Unit')),
                ('price_select_date', models.DateField(verbose_name='Price Change Date')),
                ('resource_base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Price')),
                ('resource_discount_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Discount Price')),
                ('actual_base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Actual Base Price')),
                ('team', models.CharField(choices=[('manager_procurement', 'Manager Procurement')], default='manager_procurement', help_text='Team responsible for this rp', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this RBP record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbps_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_procurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbps', to=settings.AUTH_USER_MODEL, verbose_name='Manager Procurement')),
                ('project_name_rbp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbp_project_name_rbp', to='project.project', verbose_name='Project Name')),
                ('resource_name_rbp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbp_resource_name_rbp', to='resource.resource', verbose_name='Resource Name')),
                ('supplier_name_rbp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbp_supplier_name_rbp', to='supplier.supplier', verbose_name='Supplier Name')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this RBP record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbps_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Resource Price',
                'verbose_name_plural': 'Resource Prices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RbpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_procurement', 'Manager Procurement')], default='manager_procurement', help_text="Defines the user's role in RBP operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rbp_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RBP Role Profile',
                'verbose_name_plural': 'RBP Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
