# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proposal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pfp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pfp', models.TextField(help_text='Front Page of Proposal', verbose_name='Proposal Front Page')),
                ('submit_to_pfp', models.TextField(help_text='Submit of Proposal To', verbose_name='Proposal Submit To')),
                ('submit_by_pfp', models.TextField(help_text='Submit of Proposal By', verbose_name='Proposal Submit By')),
                ('team', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text='Team responsible for this PFP', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer_name_proposal', models.CharField(max_length=255)),
                ('proposal_prepare_date', models.DateField()),
                ('proposal_no', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfps_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pfps', to=settings.AUTH_USER_MODEL, verbose_name='Manager Sales')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pfp_record', to='proposal.proposal', verbose_name='Linked Proposal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pfps_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'PFP',
                'verbose_name_plural': 'PFPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PfpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text="Defines the user's role in pfp operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pfp_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PFP Role Profile',
                'verbose_name_plural': 'PFP Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
