# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_date_stc', models.DateField(help_text='Date of STC PO', verbose_name='PO Date')),
                ('po_no_stc', models.CharField(help_text='Number of STC PO', max_length=20, verbose_name='PO No')),
                ('vat_ait_stc', models.CharField(choices=[('Include', 'Include'), ('Exclude', 'Exclude')], default='Include', help_text='VAT/AIT inclusion status', max_length=10, verbose_name='VAT/AIT')),
                ('delivery_term_stc', models.TextField(help_text='Terms of delivery', verbose_name='Delivery Term')),
                ('payment_term_stc', models.TextField(help_text='Terms of payment', verbose_name='Payment Term')),
                ('warranty_term_stc', models.TextField(help_text='Terms of warranty', verbose_name='Warranty Term')),
                ('team', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text='Team responsible for this STC PO', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stcs_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stcs', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('project_name_stc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stc_project_name_stc', to='project.project', verbose_name='Project Name')),
                ('supplier_name_stc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stc_supplier_name_stc', to='supplier.supplier', verbose_name='Supplier Name')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stcs_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'STC',
                'verbose_name_plural': 'STCs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StcProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text="Defines the user's role in stc operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'STC Role Profile',
                'verbose_name_plural': 'STC Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
