# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_information_collect_pt', models.CharField(choices=[('Sales Person-A', 'Sales Person-A'), ('Sales Person-B', 'Sales Person-B'), ('Sales Person-C', 'Sales Person-C'), ('Sales Person-D', 'Sales Person-D')], help_text='Source from which proposal information is collected', max_length=20, verbose_name='Proposal Information Source')),
                ('description_work_pt', models.TextField(help_text='Detailed description of the work in the proposal', verbose_name='Work Description')),
                ('total_proposal_pt', models.DecimalField(decimal_places=0, default=1, help_text='Total proposal amount (fixed to 1)', max_digits=14, verbose_name='Total Proposal')),
                ('prepare_date_pt', models.DateField(help_text='Date when the proposal was prepared', verbose_name='Prepare Date')),
                ('submit_date_pt', models.DateField(help_text='Date when the proposal was submitted', verbose_name='Submit Date')),
                ('submit_year_pt', models.PositiveIntegerField(help_text='Year of submission', verbose_name='Submit Year')),
                ('status_proposal_pt', models.CharField(choices=[('Award', 'Award'), ('Not Award', 'Not Award'), ('Pending', 'Pending')], help_text='Proposal for Status', max_length=20, verbose_name='Status Proposal')),
                ('proposal_award_pt', models.IntegerField(default=0, help_text='1 = Award, 0 = Not Award or Pending', verbose_name='Proposal Award')),
                ('team', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text='Team responsible for this proposal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('client_name_pt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt_client_name_pt', to='client.client', verbose_name='Client Name')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this proposal record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pt_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Manager Sales')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this proposal record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'PT Proposal',
                'verbose_name_plural': 'PT Proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PtProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_sales', 'Manager Sales')], default='manager_sales', help_text="Defines the user's role in pt operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pt_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PT Role Profile',
                'verbose_name_plural': 'PT Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
