# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(help_text='Name of the project', max_length=100, unique=True, verbose_name='Project Name')),
                ('project_address', models.CharField(help_text='Project site address', max_length=200, verbose_name='Project Address')),
                ('contact_person_name', models.CharField(help_text='Primary contact person for the project', max_length=100, verbose_name='Contact Person Name')),
                ('contact_person_number', models.CharField(help_text='Phone number of the contact person', max_length=20, verbose_name='Contact Person Number')),
                ('team', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text='Team responsible for this project', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this project record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this project record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text="Defines the user's role in project operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Role Profile',
                'verbose_name_plural': 'Project Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
