# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('resource', '0001_initial'),
        ('supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Po',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_date', models.DateField(help_text='Date of PO', verbose_name='PO Date')),
                ('po_no', models.CharField(help_text='No of PO', max_length=20, verbose_name='PO No')),
                ('resource_unit_po', models.CharField(help_text='Unit of the resource (auto or manual entry)', max_length=20, verbose_name='Resource Unit')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of the resource', max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated as Quantity × Unit Price', max_digits=14)),
                ('delivery_date', models.DateField(help_text='Date of Delivery', verbose_name='Delivery Date')),
                ('team', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text='Team responsible for this PO', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('project_name_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_project_name_po', to='project.project', verbose_name='Project Name')),
                ('resource_name_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_resource_name_po', to='resource.resource', verbose_name='Resource Name')),
                ('supplier_name_po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_supplier_name_po', to='supplier.supplier', verbose_name='Supplier Name')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'PO',
                'verbose_name_plural': 'POs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text="Defines the user's role in po operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='po_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PO Role Profile',
                'verbose_name_plural': 'PO Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
