# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Name of the company', max_length=100, unique=True, verbose_name='Company Name')),
                ('company_address', models.CharField(help_text='Enter the company address', max_length=255, verbose_name='Company Address')),
                ('company_email', models.EmailField(help_text='Enter the official company email address', max_length=254, verbose_name='Company Email')),
                ('company_contact_no', models.CharField(help_text='Enter the company phone/mobile number', max_length=20, verbose_name='Company Contact Number')),
                ('team', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text='Team responsible for this company', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this company record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this company record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text="Defines the user's role in company operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Role Profile',
                'verbose_name_plural': 'Company Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
