# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_supplier', models.CharField(help_text='Name of the supplier', max_length=100, unique=True, verbose_name='Supplier Name')),
                ('supplier_contact_person', models.CharField(help_text="Enter the supplier contact person's name", max_length=100, verbose_name='Supplier Contact Person')),
                ('supplier_address', models.CharField(help_text="Enter the supplier's address", max_length=200, verbose_name='Supplier Address')),
                ('supplier_contact_number', models.CharField(help_text='Phone number of the supplier', max_length=20, verbose_name='Supplier Contact Number')),
                ('team', models.CharField(choices=[('manager_construction', 'Manager Construction'), ('gm_construction', 'GM Construction')], default='manager_construction', help_text='Team responsible for the supplier', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this supplier record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this suppler record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_construction', 'Manager Construction'), ('gm_construction', 'GM Construction')], default='manager_construction', help_text="Defines the user's role in supplier operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier Role Profile',
                'verbose_name_plural': 'Supplier Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
