# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rwc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_date', models.DateField()),
                ('requisition_no', models.CharField(blank=True, max_length=50)),
                ('delivery_date', models.DateField()),
                ('team', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text='Team responsible for this rwc', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_address', models.CharField(blank=True, max_length=250)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_contact_no', models.CharField(blank=True, max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this rwc record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rwcs_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rwcs', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('project_name_rwc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rwc_project_name_rwc', to='project.project', verbose_name='Project Name')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this rwc record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rwcs_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Rwc',
                'verbose_name_plural': 'Rwcs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RwcProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text="Defines the user's role in rwc operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rwc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rwc Role Profile',
                'verbose_name_plural': 'Rwc Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
