# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name_ws', models.CharField(help_text='Name of the project', max_length=100, verbose_name='Project Name')),
                ('task_name_ws', models.CharField(help_text='Name of the task', max_length=100, verbose_name='Task Name')),
                ('planned_start', models.DateField()),
                ('planned_finish', models.DateField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('actual_progress', models.PositiveIntegerField(default=0, verbose_name='Actual Progress')),
                ('team', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text='Team responsible for this ws', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated', verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this ws record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wss_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wss', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this ws record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wss_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'WS',
                'verbose_name_plural': 'WSs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text="Defines the user's role in ws operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ws_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WS Role Profile',
                'verbose_name_plural': 'WS Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
