# Generated by Django 5.2.1 on 2026-05-27 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('resource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_date_pr', models.DateField(help_text='Date of Requisition', verbose_name='Requisition Date')),
                ('requisition_no_pr', models.CharField(help_text='No of Requisition', max_length=20, verbose_name='Requisition No')),
                ('resource_unit_pr', models.CharField(help_text='Unit of the resource (auto or manual entry)', max_length=20, verbose_name='Resource Unit')),
                ('quantity_pr', models.DecimalField(decimal_places=2, help_text='Quantity of the resource', max_digits=10, verbose_name='Quantity')),
                ('delivery_date_pr', models.DateField(help_text='Date of Delivery', verbose_name='Delivery Date')),
                ('remarks_pr', models.TextField(blank=True, default='NA', help_text='Additional notes or comments for this PR', null=True, verbose_name='Remarks')),
                ('team', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text='Team responsible for this PR', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('manager_construction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prs', to=settings.AUTH_USER_MODEL, verbose_name='Manager Construction')),
                ('project_name_pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs', to='project.project', verbose_name='Project Name')),
                ('resource_name_pr', models.ForeignKey(blank=True, help_text='Select the resource', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prs', to='resource.resource', verbose_name='Resource Name')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prs_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'PR',
                'verbose_name_plural': 'PRs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager_construction', 'Manager Construction')], default='manager_construction', help_text="Defines the user's role in PR operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pr_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PR Role Profile',
                'verbose_name_plural': 'PR Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
